### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by alexpriceonline** [alexpriceonline/Everydo#7]
## Todo
- [ ] Talk about what I believe and what problem the app solves.
- [ ] Create a `.gif` to show it in action
- [ ] Explain how to use it on your own sever
